instruction_generators:
  l15:
    config:
      difficulty: "level_15"
      max_rectangles: 15
      width: 20
      height: 20
      seed: 42
      generation_ratio: 1.0 

global_config:
  class_name: "internbootcamp.bootcamps.rectangle_count.instruction_generator.RectangleCountInstructionGenerator"
  default_split_samples:
    train: 100
    test: 10
  shuffle: true
  gen_parquet: true
